services:
  db_claves:
    image: mysql:8.0
    container_name: db_claves
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data_clients:/var/lib/mysql
    ports:
      - '${DOCKER_DB_PORT}:3307'
    networks:
      - service_network

volumes:
  db_data_clients:

